image: node:lts

pages: # The job name MUST be 'pages' for GitLab Pages to recognize it
  stage: deploy # Typically runs in the deploy stage
  script:
    - yarn install
    - yarn predeploy
    - rm -rf public
    - mv dist public # GitLab Pages will serve content from the 'public' directory
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
